import React from 'react';

export const SELLER = { name: 'Webfabrikk Maciej Rydz', registration: '934 291 735', address: 'Transistorfaret 2, 1396 Billingstad, Norwegia', email: 'aimarketingagencynorge@gmail.com' };

export function LegalLinks() {
  return <footer className="p-6 text-sm text-slate-400 text-center space-y-3"><p>{SELLER.name} · Org.nr {SELLER.registration}</p><nav className="flex flex-wrap justify-center gap-5"><a className="underline" href="/regulamin">Regulamin i odstąpienie</a><a className="underline" href="/prywatnosc">Polityka prywatności</a><a className="underline" href={`mailto:${SELLER.email}`}>Kontakt i reklamacje</a></nav></footer>;
}

export default function LegalPage({ privacy }: { privacy: boolean }) {
  const sections = privacy ? [
    ['Administrator i kontakt', `${SELLER.name}, ${SELLER.address}, numer organizacyjny ${SELLER.registration}. Kontakt w sprawach danych: ${SELLER.email}.`],
    ['Dane i cele', 'Przetwarzamy dane konta Google (identyfikator, nazwę, e-mail i zdjęcie profilu), informacje o marce, przesłane obrazy, prompty i zapisane treści, saldo kredytów, historię operacji oraz dane abonamentu. Dane konta i materiały służą wykonaniu umowy i udostępnieniu generatora. Rozliczenia przechowujemy także w celu wykonania obowiązków prawnych. Logi bezpieczeństwa oraz pseudonimowy identyfikator karty służą ochronie przed nadużyciami w naszym prawnie uzasadnionym interesie.'],
    ['Dostawcy', 'Logowanie, przechowywanie i generowanie obsługują usługi Google (Firebase, Google Cloud i Gemini). Prompty i obrazy potrzebne do generowania są przekazywane Google. Płatności i dane karty obsługuje Stripe zgodnie ze swoją polityką prywatności. SociAI nie zapisuje numeru karty ani kodu CVC. Zapisuje identyfikatory klienta i abonamentu oraz zabezpieczony skrót identyfikatora karty do kontroli jednorazowego okresu próbnego.'],
    ['Miejsce przetwarzania', 'Infrastruktura aplikacji korzysta z Google Cloud w Stanach Zjednoczonych. Dostawcy mogą przetwarzać dane poza EOG w oparciu o odpowiednie mechanizmy prawne transferu, w tym standardowe klauzule umowne. Nie przesyłaj danych szczególnych kategorii ani cudzych danych bez podstawy prawnej. Wygenerowane pliki mają adresy z tokenem dostępu: osoba posiadająca taki adres może otworzyć plik.'],
    ['Przechowywanie i usuwanie', 'Profil i materiały zachowujemy przez czas utrzymywania konta, również po anulowaniu abonamentu, aby umożliwić eksport. O usunięcie konta i materiałów możesz poprosić e-mailem. Dane rozliczeniowe zachowujemy przez okres wymagany przepisami, a dane konieczne do ochrony przed nadużyciami i dochodzenia roszczeń przez czas uzasadniony tym celem.'],
    ['Twoje prawa', 'Możesz wystąpić o dostęp, sprostowanie, usunięcie, ograniczenie przetwarzania i przeniesienie danych oraz wnieść sprzeciw wobec przetwarzania opartego na uzasadnionym interesie. Możesz złożyć skargę do Datatilsynet lub właściwego organu ochrony danych w kraju zamieszkania. Podanie danych konta jest konieczne do korzystania z usługi. Nie podejmujemy decyzji wywołujących skutki prawne na podstawie wygenerowanych treści.'],
    ['Przechowywanie w przeglądarce', 'Aplikacja korzysta z pamięci przeglądarki i mechanizmów sesji potrzebnych do logowania, zapisania ustawień i obsługi konta. Wyloguj się na współdzielonym urządzeniu. Ta wersja aplikacji nie dodaje reklamowych plików cookie.'],
  ] : [
    ['Sprzedawca', `${SELLER.name}, ${SELLER.address}, Org.nr ${SELLER.registration}. Kontakt, reklamacje i odstąpienie: ${SELLER.email}.`],
    ['Usługa', 'SociAI Studio pomaga tworzyć plany publikacji, teksty i grafiki z użyciem AI. Konto wymaga logowania Google i aktualnej przeglądarki z internetem. Użytkownik sprawdza materiały przed ich użyciem. Usługa nie gwarantuje zasięgów, sprzedaży ani wyłączności wygenerowanych treści. Publikacja na platformach społecznościowych nie jest objęta samym zakupem abonamentu.'],
    ['Cena i kredyty', 'Abonament kosztuje 49 zł brutto miesięcznie i obejmuje 500 FC na okres. Kredyty nie są pieniądzem i nie podlegają wymianie na gotówkę. Koszt operacji jest widoczny w aplikacji. Niewykorzystane kredyty nie przechodzą na kolejny okres. Po ich wyczerpaniu generowanie jest wstrzymane; nie pobieramy przez to wcześniejszej opłaty.'],
    ['Próba i zawarcie umowy', 'Nowe uprawnione konto i karta mogą otrzymać 7 dni oraz maksymalnie 500 FC gratis. Po próbie abonament odnawia się za 49 zł miesięcznie. Wcześniej wykorzystana próba oznacza płatny start; informację o tym pokazujemy przed zakupem. Sama rejestracja karty nie uruchamia abonamentu. Umowa powstaje po zaakceptowaniu warunków i potwierdzeniu abonamentu w Stripe. Dostęp uruchamia się po potwierdzeniu próby lub płatności.'],
    ['Anulowanie', 'Odnowienie można wyłączyć w panelu „Zarządzaj abonamentem / anuluj odnowienie”. Anuluj przed końcem próby, aby uniknąć pierwszej opłaty. Anulowanie opłaconego abonamentu pozostawia dostęp do końca okresu. Zapisane materiały pozostają do eksportu do czasu usunięcia konta. Problemy z panelem zgłaszaj e-mailem.'],
    ['Odstąpienie i reklamacje', 'Konsument może odstąpić od umowy zawartej na odległość w ciągu 14 dni od jej zawarcia. Nie wymagamy zrzeczenia się tego prawa. Wyślij e-mail z adresem konta i oświadczeniem o odstąpieniu; potwierdzimy otrzymanie i rozliczymy zwrot zgodnie z obowiązującymi przepisami. Przykład: „Odstępuję od umowy SociAI Studio zawartej dnia …, konto …, imię i nazwisko …”. Reklamację opisz wraz z datą i skutkiem problemu. Odpowiemy w ciągu 14 dni. Ustawowe prawa dotyczące zgodności usługi z umową pozostają zachowane.'],
    ['Materiały i odpowiedzialność', 'Przesyłaj materiały, do których masz prawa, i nie wykorzystuj usługi do działań bezprawnych. Zachowujesz prawa do swoich materiałów; udzielasz zgody na ich przetwarzanie w zakresie potrzebnym do działania usługi. Treści AI mogą zawierać błędy i wymagają weryfikacji. Nie wyłączamy odpowiedzialności, której nie można wyłączyć na podstawie obowiązującego prawa.'],
    ['Zmiany i kontakt', 'Zmiany ceny lub istotnych warunków nie działają wstecz. Poinformujemy o nich przed zastosowaniem do kolejnego okresu, umożliwiając rezygnację. Obowiązkowe prawa konsumenta wynikające z prawa jego kraju zamieszkania pozostają zachowane.'],
  ];
  return <main className="min-h-screen bg-[#0A0A12] text-slate-200 px-6 py-12"><article className="max-w-3xl mx-auto"><a className="text-cyan-300 underline" href="/">← SociAI Studio</a><h1 className="text-4xl font-bold mt-8 mb-3">{privacy ? 'Polityka prywatności' : 'Regulamin SociAI Studio'}</h1><p className="text-slate-400">Wersja z 19 września 2026</p>{sections.map(([title, body]) => <section key={title} className="mt-8"><h2 className="text-xl font-semibold mb-3">{title}</h2><p className="leading-7">{body}</p></section>)}<LegalLinks /></article></main>;
}
